language: java

sudo: required

services:
  - docker

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository/

install:
  - git clone https://github.com/kbastani/spring-boot-graph-processing-example.git build
  - sudo bash ./build/integration-test/integration-test.sh

script:
  - sudo bash ./build/integration-test/build.sh
