server:
  port: 8888

management:
  context-path: /admin

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          basedir: target/config
  profiles:
    active: production

---
spring:
  profiles: production
eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_PORT_8761_TCP_ADDR:172.17.0.8}:8761/eureka/
