spring.profiles.active: 'production'
---
server:
  port: 8080
  servletPath: /
spring:
  neo4j:
    port: 7474
    host: 'graphdb'
  rabbitmq:
    port: 5672
    host: 'rabbit'
    username: guest
    password: guest
    listener:
      max-concurrency: 1
      prefetch: 1
      acknowledge-mode: auto
      auto-startup: true
    dynamic: true
  social:
    twitter:
      accessTokenSecret: 'GIra8EGlwPB6UjyG2ZfbtPdArPmWM3FtinZdXUrwlriit'
      accessToken: '744537288625917952-rPFHy7MnPhl0z4zVOmGKOl4uT4zeNmM'
      appSecret: 'y7l4HOksMOGttU3kFBEDavGewjMJZdj0BfEAw7H5hXzIOnbXPZ'
      appId: 'wndX3iT34jCWoPXj8BQRTfiTm'
  profiles: 'production'
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true
---
server:
  port: 8080
  servletPath: /
spring:
  neo4j:
    port: 7474
    host: '192.168.99.100'
  rabbitmq:
    port: 5672
    host: 'localhost'
    username: guest
    password: guest
    listener:
      max-concurrency: 1
      prefetch: 1
      acknowledge-mode: auto
      auto-startup: true
    dynamic: true
  social:
    twitter:
      accessTokenSecret: 'GIra8EGlwPB6UjyG2ZfbtPdArPmWM3FtinZdXUrwlriit'
      accessToken: '744537288625917952-rPFHy7MnPhl0z4zVOmGKOl4uT4zeNmM'
      appSecret: 'y7l4HOksMOGttU3kFBEDavGewjMJZdj0BfEAw7H5hXzIOnbXPZ'
      appId: 'wndX3iT34jCWoPXj8BQRTfiTm'
  profiles: 'development'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
---
server:
  port: 8080
  servletPath: /
spring:
  neo4j:
    port: 7474
    host: '192.168.99.100'
  rabbitmq:
    port: 5672
    host: 'localhost'
    username: guest
    password: guest
    listener:
      max-concurrency: 1
      prefetch: 1
      acknowledge-mode: auto
      auto-startup: true
    dynamic: true
  social:
    twitter:
      accessTokenSecret: 'GIra8EGlwPB6UjyG2ZfbtPdArPmWM3FtinZdXUrwlriit'
      accessToken: '744537288625917952-rPFHy7MnPhl0z4zVOmGKOl4uT4zeNmM'
      appSecret: 'y7l4HOksMOGttU3kFBEDavGewjMJZdj0BfEAw7H5hXzIOnbXPZ'
      appId: 'wndX3iT34jCWoPXj8BQRTfiTm'
  profiles: 'test'
eureka:
  client:
    enabled: false
